**Тема:** Дії з векторами та матрицями. Бібліотека NumPy.

20 завдань. Після кожної умови залишено порожню комірку для самостійного написання коду.

У наборі використано інші числові дані, а також додано нові операції з NumPy.

In [2]:
import numpy as np
np.__version__

'2.1.3'

## Завдання 1. Додавання, віднімання та множення векторів на число

Дано вектори:
```python
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])
```

1. Знайдіть `a + b`.
2. Знайдіть `a - b`.
3. Помножте вектор `a` на число `4`.
4. Помножте вектор `b` на число `-2`.
5. Обчисліть поелементний добуток `a * b`.

In [3]:
a = np.array([7, -2, 5, 9])
b = np.array([3, 6, -1, 4])

print("a + b =", a + b)
print("a - b =", a - b)
print("4a =", 4 * a)
print("-2b =", -2* b)
print("a * b =", a * b)

a + b = [10  4  4 13]
a - b = [ 4 -8  6  5]
4a = [28 -8 20 36]
-2b = [ -6 -12   2  -8]
a * b = [ 21 -12  -5  36]


## Завдання 2. Скалярний добуток і довжина векторів

Дано вектори:
```python
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])
```

1. Обчисліть скалярний добуток двома способами: `np.dot()` і оператором `@`.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами.

In [4]:
u = np.array([2,-3, 6])
v = np.array([5, 1, 4])

dot1 = np.dot(u, v)
dot2 = u @ v
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
cos_angle = dot1 / (norm_u * norm_v)

print("np.dot:", dot1)
print("@:", dot2)
print("Нормa u:", norm_u)
print ("Hoрма v:", norm_v)
print ("Косинус кута: ", cos_angle)

np.dot: 31
@: 31
Нормa u: 7.0
Hoрма v: 6.48074069840786
Косинус кута:  0.6833434069749784


## Завдання 3. Основні дії з матрицями

Дано матриці:
```python
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])
```

1. Обчисліть `A + B`.
2. Обчисліть `A - B`.
3. Обчисліть поелементний добуток `A * B`.
4. Помножте матрицю `A` на число `5`.
5. Знайдіть транспоновану матрицю `A`.

In [5]:
A = np.array([
    [3, 5, -1],
    [2, 0, 4]
])

B = np.array([
    [1, -2, 6],
    [7, 3, 2]
])

print("A + B:\n", A + B)
print("\nA - B:\n", A - B)
print("\nA * B:\n", A * B)
print("\n5A:\n", 5 * A)
print("\nA.T:\n", A.T)

A + B:
 [[4 3 5]
 [9 3 6]]

A - B:
 [[ 2  7 -7]
 [-5 -3  2]]

A * B:
 [[  3 -10  -6]
 [ 14   0   8]]

5A:
 [[15 25 -5]
 [10  0 20]]

A.T:
 [[ 3  2]
 [ 5  0]
 [-1  4]]


## Завдання 4. Матричне множення

Дано матриці:
```python
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])
```

1. Обчисліть матричний добуток `A @ B`.
2. Визначте форму результату.
3. Обчисліть елемент результату з індексами `[0, 1]` вручну через відповідний рядок `A` і стовпець `B` та перевірте його.

In [10]:
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])

C = A @ B
print("A @ B:\n", C)
print("Розмір матриці:", C.shape)

manual = A[0, 0] * B[0, 1] + A[0, 1] * B[1, 1] + A[0, 2] * B[2, 1]

print("C[0, 1] =", C[0, 1])
print("Ручна перевірка =", manual)

A @ B:
 [[17  7]
 [32  5]]
Розмір матриці: (2, 2)
C[0, 1] = 7
Ручна перевірка = 7


## Завдання 5. Циклічний зсув вектора

Дано вектор:
```python
v = np.array([12, 7, 19, 4, 11, 8])
```

1. Виконайте циклічний зсув на 2 позиції вправо.
2. Виконайте циклічний зсув на 3 позиції вліво.
3. Відновіть початковий вектор із результату першого зсуву.

Використайте `np.roll()`.

In [11]:
v = np.array([12, 7, 19, 4, 11, 8])

right_2 = np.roll(v, 2)
left_3 = np.roll(v, -3)
restored = np.roll(right_2, -2)

print ("Вправо на 2:", right_2)
print ("Вліво на 3:", left_3)
print ("Відновлений: ", restored)

Вправо на 2: [11  8 12  7 19  4]
Вліво на 3: [ 4 11  8 12  7 19]
Відновлений:  [12  7 19  4 11  8]


## Завдання 6. Сортування та індекси

Дано вектор:
```python
v = np.array([42, 17, 29, 8, 35, 23])
```

1. Відсортуйте елементи за зростанням.
2. Відсортуйте елементи за спаданням.
3. Отримайте індекси початкового вектора, які задають порядок елементів від найбільшого до найменшого.

Використайте `np.sort()` та `np.argsort()`.

In [12]:
v = np.array([42, 17, 29, 8, 35, 23])

ascending = np.sort(v)
descending = ascending[::-1]
indices_desc = np.argsort(v)[::-1]

print("За зростанням:", ascending)
print("За спаданням:", descending)
print("Індекси:", indices_desc)
print("Перевірка:", v[indices_desc])

За зростанням: [ 8 17 23 29 35 42]
За спаданням: [42 35 29 23 17  8]
Індекси: [0 4 2 5 1 3]
Перевірка: [42 35 29 23 17  8]


## Завдання 7. Обмеження значень

Дано вектор:
```python
v = np.array([-12, -4, 3, 18, 27, 35, 48])
```

Обмежте всі значення діапазоном від `-5` до `30`: значення, менші за `-5`, мають стати `-5`, а більші за `30` — `30`.

Додатково визначте індекси елементів, які були змінені.

Використайте `np.clip()`.

In [13]:
v = np.array([-12, -4, 3, 18, 27, 35, 48])

clipped = np.clip(v, -5, 30)
changed = np.where(v != clipped) [0]

print("Після обмеження:", clipped)
print("Змінені індекси:", changed)

Після обмеження: [-5 -4  3 18 27 30 30]
Змінені індекси: [0 5 6]


## Завдання 8. Унікальні значення та частоти

Дано вектор:
```python
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])
```

1. Знайдіть усі унікальні значення.
2. Визначте кількість появ кожного значення.
3. Знайдіть значення, яке трапляється найчастіше.

Використайте `np.unique(..., return_counts=True)`.

In [14]:
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])

values, counts = np.unique(v, return_counts=True)
most_frequent = values [np.argmax(counts)]

print("Унікальні:", values)
print("Частоти:", counts)
print("Найчастіше значення:", most_frequent)

Унікальні: [2 4 7 9]
Частоти: [3 3 4 1]
Найчастіше значення: 7


## Завдання 9. Поворот матриці

Дано матрицю:
```python
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])
```

Отримайте:
1. матрицю, повернуту на 90° за годинниковою стрілкою;
2. матрицю, повернуту на 180°;
3. матрицю, повернуту на 90° проти годинникової стрілки.

Використайте `np.rot90()`.

In [16]:
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])

print("99 за годинниковою: \n", np.rot90(A, -1))
print("\n180°:\n", np.rot90(A, 2))
print ("\n90° проти годинникової: \n", np.rot90(A, 1))

99 за годинниковою: 
 [[18 10  2]
 [20 12  4]
 [22 14  6]
 [24 16  8]]

180°:
 [[24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]

90° проти годинникової: 
 [[ 8 16 24]
 [ 6 14 22]
 [ 4 12 20]
 [ 2 10 18]]


## Завдання 10. Додавання рамки до матриці

Дано матрицю:
```python
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])
```

1. Додайте навколо матриці рамку шириною 1 елемент, заповнену значенням `-1`.
2. Окремо створіть рамку шириною 2 елементи, заповнену нулями.
3. Виведіть форми отриманих матриць.

Використайте `np.pad()`.

In [20]:
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])

border1 = np.pad(A, 1, mode="constant", constant_values=-1)
border2 = np.pad(A, 2, mode="constant", constant_values=0)

print("Рамка 1:\n", border1)
print("Форма:", border1.shape)
print("\nРамка 2:\n", border2)
print("Форма:", border2.shape)

Рамка 1:
 [[-1 -1 -1 -1 -1]
 [-1  6  1  8 -1]
 [-1  3  5  2 -1]
 [-1  9  4  7 -1]
 [-1 -1 -1 -1 -1]]
Форма: (5, 5)

Рамка 2:
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 6 1 8 0 0]
 [0 0 3 5 2 0 0]
 [0 0 9 4 7 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Форма: (7, 7)


## Завдання 11. Перестановка рядків і стовпців

Дано матрицю:
```python
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])
```

1. Переставте рядки відповідно до `row_order`.
2. Після цього переставте стовпці відповідно до `col_order`.
3. За допомогою обернених перестановок відновіть початкову матрицю.

Для побудови оберненої перестановки використайте `np.argsort()`.

In [25]:
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])

permuted = A[row_order][:, col_order]
restored = permuted[np.argsort(row_order)][:, np.argsort(col_order)]

print("Після перестановок: \n", permuted)
print("\nВідновлена:\n", restored)
print("Збіг:", np.array_equal(A, restored))

Після перестановок: 
 [[34 32 31 33]
 [14 12 11 13]
 [44 42 41 43]
 [24 22 21 23]]

Відновлена:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
Збіг: True


## Завдання 12. Трикутні частини матриці

Дано матрицю:
```python
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])
```

1. Отримайте верхню трикутну частину разом із головною діагоналлю.
2. Отримайте нижню трикутну частину разом із головною діагоналлю.
3. Отримайте строго верхню та строго нижню частини.
4. Відновіть початкову матрицю з нижньої та строго верхньої частин.

Використайте `np.triu()` та `np.tril()`.

In [26]:
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])

upper = np.triu(A)
lower = np.tril(A)
strict_upper = np.triu(A, 1)
strict_lower = np.tril(A, -1)
restored = lower + strict_upper

print("Bepхня: \n", upper)
print ("\nНижня: \n", lower)
print ("\nСтрого верхня:\n", strict_upper)
print("\nСтрого нижня: \n", strict_lower)
print ("\nBідновлена:\n", restored)

Bepхня: 
 [[4 1 7 2]
 [0 3 5 8]
 [0 0 6 1]
 [0 0 0 3]]

Нижня: 
 [[4 0 0 0]
 [6 3 0 0]
 [9 2 6 0]
 [5 7 4 3]]

Строго верхня:
 [[0 1 7 2]
 [0 0 5 8]
 [0 0 0 1]
 [0 0 0 0]]

Строго нижня: 
 [[0 0 0 0]
 [6 0 0 0]
 [9 2 0 0]
 [5 7 4 0]]

Bідновлена:
 [[4 1 7 2]
 [6 3 5 8]
 [9 2 6 1]
 [5 7 4 3]]


## Завдання 13. Зовнішній добуток векторів

Дано вектори:
```python
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])
```

1. Побудуйте матрицю зовнішнього добутку.
2. Визначте її форму.
3. Перевірте, що елемент `[2, 1]` дорівнює `a[2] * b[1]`.

Використайте `np.outer()`.

In [27]:
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])

outer = np.outer(a, b)

print("Зовнішній добуток: \n", outer)
print("Форма:", outer.shape)
print("Перевірка:", outer[2, 1], "=", a[2] * b[1])

Зовнішній добуток: 
 [[ 6 10 16]
 [12 20 32]
 [21 35 56]
 [27 45 72]]
Форма: (4, 3)
Перевірка: 35 = 35


## Завдання 14. Добуток Кронекера

Дано матриці:
```python
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])
```

1. Обчисліть добуток Кронекера `A` і `B`.
2. Обчисліть добуток Кронекера `B` і `A`.
3. Порівняйте результати та їх форми.

Використайте `np.kron()`.

In [28]:
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])

AB = np.kron(A, B)
BA = np.kron(B, A)

print("kron(A, B):\n", AB)
print("\nkron(B, A):\n", BA)
print("\nФорми:", AB.shape, BA.shape)
print("Матриці однакові:", np.array_equal(AB, BA))

kron(A, B):
 [[ 2  8  1  4]
 [ 4  0  2  0]
 [ 0  0  3 12]
 [ 0  0  6  0]]

kron(B, A):
 [[ 2  1  8  4]
 [ 0  3  0 12]
 [ 4  2  0  0]
 [ 0  6  0  0]]

Форми: (4, 4) (4, 4)
Матриці однакові: False


## Завдання 15. Комутатор двох матриць

Для кожної пари матриць обчисліть комутатор
\[
[A,B] = AB - BA.
\]

Перша пара:
```python
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])
```

Друга пара:
```python
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])
```

Визначте, для якої пари виконується `AB = BA`. Для перевірки використайте `np.allclose()`.

In [29]:
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])

A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])

comm1 = A1 @ B1 - B1 @ A1
comm2 = A2 @ B2 - B2 @ A2

print("Комутатор 1:\n", comm1)
print("AB = ВА для пари 1:", np.allclose(comm1, 0))
print("\nКомутатор 2:\n", comm2)
print("AB = ВА для пари 2:", np.allclose(comm2, 0))

Комутатор 1:
 [[0 0]
 [0 0]]
AB = ВА для пари 1: True

Комутатор 2:
 [[ 0 -6]
 [-3  0]]
AB = ВА для пари 2: False


## Завдання 16. Квадратична форма

Дано симетричну матрицю:
```python
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])
```

1. Обчисліть квадратичну форму `xᵀAx`.
2. Для трьох векторів
```python
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])
```
обчисліть значення квадратичної форми для кожного рядка без циклу.

Для другого пункту використайте `np.einsum()`.

In [30]:
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])

q = x @ A @ x

X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])

q_all = np.einsum("ij,jk,ik->i", X, A, X)

print("x^T A x =", q)
print("Для всіх рядків:", q_all)

x^T A x = 35
Для всіх рядків: [35 17 27]


## Завдання 17. Степінь матриці

Дано матрицю:
```python
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])
```

1. Обчисліть `A²`.
2. Обчисліть `A³`.
3. Перевірте, що `A³ = A² @ A`.

Використайте `np.linalg.matrix_power()`.

In [31]:
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])

A2 = np.linalg.matrix_power (A, 2)
A3 = np.linalg.matrix_power(A, 3)

print("A^2:\n", A2)
print("\nA^3:\n", A3)
print("\nПепевірка:", np.array_equal(A3, A2 @ A))

A^2:
 [[1 2 1]
 [1 1 2]
 [2 1 1]]

A^3:
 [[2 3 3]
 [3 2 3]
 [3 3 2]]

Пепевірка: True


## Завдання 18. Ранг матриці

Дано дві матриці:
```python
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])
```

1. Знайдіть ранг кожної матриці.
2. Визначте, яка з них має повний ранг.

Використайте `np.linalg.matrix_rank()`.

In [34]:
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])

rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)

print("rank(A) =", rank_A)
print("rank(B) =", rank_B)
print("A має повний ранг:", rank_A == min(A.shape))
print("B має повний ранг:", rank_B == min(B.shape))

rank(A) = 3
rank(B) = 2
A має повний ранг: True
B має повний ранг: False


## Завдання 19. Власні значення та власні вектори

Дано симетричну матрицю:
```python
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])
```

1. Знайдіть власні значення та власні вектори.
2. Перевірте співвідношення `A @ V = V * λ`.
3. Виведіть результат перевірки через `np.allclose()`.

Використайте `np.linalg.eigh()`.

In [35]:
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])

values, vectors = np.linalg.eigh(A)
left = A @ vectors
right = vectors * values

print("Власні значення:", values)
print("Власні вектори: \n", vectors)
print("Перевірка:", np.allclose(left, right))

Власні значення: [2. 7.]
Власні вектори: 
 [[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]
Перевірка: True


## Завдання 20. Метод найменших квадратів

Для точок
```python
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])
```

побудуйте пряму
\[
y \approx a + bx.
\]

1. Сформуйте матрицю ознак зі стовпця одиниць і значень `x`.
2. Знайдіть коефіцієнти `a` і `b` методом найменших квадратів.
3. Обчисліть прогнозні значення `y`.
4. Знайдіть суму квадратів залишків.

Використайте `np.linalg.lstsq()`.

In [45]:
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])

X = np.column_stack((np.ones_like(x), x))
coef, residuals, rank, s = np.linalg.lstsq(X, y, rcond=None)

a, b = coef
y_pred = X @ coef
sse = np.sum((y - y_pred) ** 2)

print("a =", a)
print("b =", b)
print("Прогноз:", y_pred)
print("Сума квадратів залишків:", sse)

a = 2.019999999999998
b = 2.0100000000000002
Прогноз: [ 2.02  4.03  6.04  8.05 10.06]
Сума квадратів залишків: 0.13099999999999973
